title: Functions17
description: >-
  Enabling Creativity, Exploration, Discussion and Learning for Developers creating the
  future of Function as a Service (FaaS) architecture.
date: August 25, 2017 in Toronto
social:
  - url: https://twitter.com/FunctionsConf
    alt: "FunctionsConf on Twitter"
    icon: "icon-twitter"
logo: /assets/logo-small.png
schema:
  type: Something
  url: functions.world
registration: https://www.eventbrite.com/e/functions17-tickets-35394300305

assets_url: /assets
speaker_images: /assets/speakers/
sponsor_images: /assets/sponsors/

url: https://2017.functions.world
markdown: kramdown
